version: 2
common:
  log_path: resources/event_logs/PurchasingExample.csv
  model_path: resources/event_logs/PurchasingExample.bpmn
  repetitions: 1
  evaluation_metrics:
    - absolute_hourly_emd
    - cycle_time_emd
    - circadian_emd
  log_ids:
    case: case_id
    activity: Activity
    resource: Resource
    start_time: start_time
    end_time: end_time
preprocessing:
  multitasking: false
structure:
  max_evaluations: 2
  mining_algorithm: sm3
  optimization_metric: n_gram_distance
  concurrency:
    - 0.0
    - 1.0
  epsilon:
    - 0.0
    - 1.0
  eta:
    - 0.0
    - 1.0
  gateway_probabilities:
    - equiprobable
    - discovery
  replace_or_joins:
    - true
    - false
  prioritize_parallelism:
    - true
    - false
calendars:
  max_evaluations: 10
  optimization_metric: absolute_hourly_emd
  resource_profiles:
    discovery_type: differentiated
    granularity: 60
    confidence:
      - 0.1
      - 0.4
    support:
      - 0.6
      - 1.0
    participation: 0.4version: 4
common:
  train_log_path: resources/event_logs/LoanApp_simplified_train.csv
  test_log_path: resources/event_logs/LoanApp_simplified_test.csv
  # model_path: resources/models/LoanApp_simplified.bpmn  # Uncomment to use this BPMN model as process model
  num_final_evaluations: 10  # Number of evaluations of the discovered BPS model.
  evaluation_metrics:  # Metrics to evaluate the discovered BPS model with.
    - 3_gram_distance
    - 2_gram_distance
    - absolute_event_distribution
    - relative_event_distribution
    - circadian_event_distribution
    - arrival_event_distribution
    - cycle_time_distribution
  log_ids:
    case: case_id
    activity: activity
    resource: resource
    start_time: Start_Time
    end_time: End_Time
    enabled_time: Enabled_Time
  clean_intermediate_files: false
preprocessing:
  multitasking: false  # Reassign activity durations when happening in multitasking.
  enable_time_concurrency_threshold: 0.5  # Concurrency threshold for the enabled time computation.
  concurrency_df: 0.75  # Concurrency thresholds for the start time (and enabled time) estimations when
  concurrency_l2l: 0.9  # the start time is missing in the train event log. Using the Heuristics Miner
  concurrency_l1l: 0.9  # concurrency oracle.
control_flow:
  optimization_metric: n_gram_distance
  num_iterations: 10  # Number of iterations to run the hyper-optimization process for control-flow discovery
  num_evaluations_per_iteration: 5  # Number of times to evaluate each iteration (using the mean of all of them)
  gateway_probabilities:  # Methods to discover the probabilities of each gateway
    - equiprobable
    - discovery
  discovery_algorithm: sm3  # Process model discovery algorithm: sm2 (Split Miner v2) or sm3 (Split Miner v3)
  epsilon:
    - 0.0
    - 1.0
  eta:
    - 0.0
    - 1.0
  replace_or_joins:
    - true
    - false
  prioritize_parallelism:
    - true
    - false
resource_model:
  optimization_metric: circadian_event_distribution
  num_iterations: 10  # Number of iterations to run the hyper-optimization process for control-flow discovery
  num_evaluations_per_iteration: 5  # Number of times to evaluate each iteration (using the mean of all of them)
  resource_profiles:
    discovery_type: differentiated  # Resource discovery type (undifferentiated, pooled, or differentiated)
    granularity:
      - 15
      - 60
    confidence:
      - 0.5
      - 0.85
    support:
      - 0.01
      - 0.3
    participation: 0.4
extraneous_activity_delays:
  optimization_metric: relative_event_distribution
  num_iterations: 1  # Number of iterations of the optimization process (if 1, direct discovery without optimization)
  num_evaluations_per_iteration: 3  # Number of times to evaluate each iteration (using the mean of all of them)