# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip: [ pytest-check ]
repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest --exitfirst -m "not integration" --durations=0
        language: system
        pass_filenames: false
        always_run: true
