[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "simod"
version = "5.2.0"
authors = [
    "Ihar Suvorau <ihar.suvorau@gmail.com>",
    "David Chapela <david.chapela@ut.ee>",
    "Manuel Camargo <manuel.camargo@ut.ee>",
]
description = "Simod is a Python tool for automated discovery of business process simulation models from event logs."
readme = "README.md"
packages = [{ include = "simod", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
click = "^8.4.2"
hyperopt = "^0.3.0"
lxml = "^6.1.1"
matplotlib = "^3.11.1"
networkx = "^3.6.1"
numpy = "^2.4.6"
pandas = "^2.3.3"
pendulum = "^3.2.0"
pydantic = "^2.13.4"
python-dotenv = "^1.2.2"
python-multipart = "^0.0.32"
pytz = "^2026.3"
PyYAML = "^6.0.3"
requests = "^2.34.2"
scipy = "^1.17.1"
statistics = "^1.0.3.5"
tqdm = "^4.70.0"
xmltodict = "^1.0.4"
prosimos = "^2.1.0"
extraneous-activity-delays = "^2.3.0"
openxes-cli-py = "^0.1.15"
pix-framework = "^0.15.0"
log-distance-measures = "^2.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.1"
pytest-cov = "^7.0.0"
memory-profiler = "^0.61.0"
pylint = "^4.0.3"
setuptools = "^80.9.0"
seaborn = "^0.13.2"
pytest-benchmark = "^5.2.3"
snakeviz = "^2.2.2"

[tool.poetry.scripts]
simod = "simod.cli:main"

[tool.ruff]
line-length = 120

[tool.black]
line-length = 120

[tool.pytest.ini_options]
markers = ["integration", "system", "manual", "benchmark", "smoke"]
