version: 2
common:
  log_path: <train_log_path>
  test_log_path: <test_log_path>
  repetitions: 10
  clean_intermediate_files: true
  evaluation_metrics:
    - dl
    - circadian_emd
    - absolute_hourly_emd
    - cycle_time_emd
    - n_gram_distance
  log_ids:
    case: case_id
    activity: activity
    resource: resource
    start_time: start_time
    end_time: end_time
    enabled_time: enabled_time
preprocessing:
  multitasking: false
  enable_time_concurrency_threshold: 0.5
control_flow:
  optimization_metric: n_gram_distance
  num_iterations: 30
  num_evaluations_per_iteration: 5
  gateway_probabilities: discovery
  mining_algorithm: sm3
  epsilon:
    - 0.1
    - 1.0
  eta:
    - 0.2
    - 0.6
  replace_or_joins:
    - true
    - false
  prioritize_parallelism:
    - true
    - false
calendars:
  optimization_metric: circadian_emd
  max_evaluations: 40
  resource_profiles:
    discovery_type: differentiated
    granularity:
      - 15
      - 60
    confidence:
      - 0.1
      - 1.0
    support:
      - 0.1
      - 1.0
    participation: 0.4
extraneous_activity_delays:
  optimization_metric: relative_emd
  num_iterations: 1
