log_path: resources/event_logs/private/ConsultaDataMining201618.xes
mining_alg: sm2
exec_mode: optimizer
repetitions: 5
sim_metric: tsd
multitasking: true
add_metrics:
- day_hour_emd
- log_mae
- dl
- mae
structure_optimizer:
  max_eval_s: 40
  concurrency:
  - 0.0
  - 1.0
  epsilon:
  - 0.0
  - 1.0
  eta:
  - 0.0
  - 1.0
  gate_management:
  - discovery
  - equiprobable
  or_rep:
  - true
  - false
  and_prior:
  - true
  - false
time_optimizer:
  max_eval_t: 20
  rp_similarity:
  - 0.5
  - 0.9
  res_dtype:
  - dt247
  - lv917
  arr_dtype:
  - dt247
  - lv917
  res_sup_dis:
  - 0.01
  - 0.3
  res_con_dis:
  - 50
  - 85
  arr_support:
  - 0.01
  - 0.1
  arr_confidence:
  - 1
  - 10
