#################################################################################################################
# Same simple configuration as 'configuration_example.yml' but providing the BPMN model                         #
#################################################################################################################
# - Increase the num_iterations to (potentially) improve the quality of that discovered model                   #
# - Visit 'complete_configuration.yml' example for a description of all configurable parameters                 #
#################################################################################################################
version: 5
##########
# Common #
##########
common:
  # Path to the event log in CSV format
  train_log_path: ../event_logs/LoanApp_simplified_train.csv.gz
  # Specify the name for each of the columns in the CSV file (XES standard by default)
  log_ids:
    case: "case_id"
    activity: "activity"
    resource: "resource"
    enabled_time: "enabled_time"  # If not present in the log, automatically computed
    start_time: "start_time"
    end_time: "end_time"
  # Use this process model and skip its discovery
  process_model_path: ../models/LoanApp_simplified.bpmn
  # Whether to discover case attributes or not
  discover_data_attributes: false
#################
# Preprocessing #
#################
preprocessing:
  # Threshold to consider two activities as concurrent when computing the enabled time (if necessary)
  enable_time_concurrency_threshold: 0.75
################
# Control-flow #
################
control_flow:
  # Metric to guide the optimization process (loss function to minimize)
  optimization_metric: two_gram_distance
  # Number of optimization iterations over the search space
  num_iterations: 1
  # Number of times to evaluate each iteration (using the mean of all of them)
  num_evaluations_per_iteration: 3
  # Methods for discovering gateway probabilities
  gateway_probabilities: discovery
##################
# Resource model #
##################
resource_model:
  # Metric to guide the optimization process (loss function to minimize)
  optimization_metric: circadian_emd
  # Number of optimization iterations over the search space
  num_iterations: 20
  # Number of times to evaluate each iteration (using the mean of all of them)
  num_evaluations_per_iteration: 3
  # Whether to discover prioritization or batching behavior
  discover_prioritization_rules: false
  discover_batching_rules: false
  # Resource profiles configuration
  resource_profiles:
    # Resource profile discovery type
    discovery_type: pool
    # Time granularity (in minutes) for the resource calendar (the higher the density of events in the log, the smaller the granularity can be)
    granularity: 60
    # Minimum confidence of the intervals in the discovered calendar (of a resource or set of resources)
    confidence:
      - 0.5
      - 0.85
    # Minimum support of the intervals in the discovered calendar (of a resource or set of resources)
    support:
      - 0.05
      - 0.5
    # Participation of a resource in the process to discover a calendar for them (gathered together otherwise)
    participation: 0.4
#####################
# Extraneous delays #
#####################
extraneous_activity_delays:
  # Method to compute the extraneous delay
  discovery_method: eclipse-aware
  # Number of optimization iterations over the search space (1 = direct discovery, no optimization stage)
  num_iterations: 1
