---
- name: Testing
  hosts: main

  tasks:
    - set_fact:
        base_dir: /home/ihar/simod_testing
        experiment_name: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
      tags: testing

    - name: Create the testing directory
      file:
        path: "{{ base_dir }}/{{ experiment_name }}"
        state: directory
      with_items:
        - "{{ base_dir }}"
        - "{{ base_dir }}/{{ experiment_name }}"
      tags: testing

    - name: Prepare Bash script for testing
      template:
        src: templates/docker_run_cmd.sh.j2
        dest: "{{ base_dir }}/{{ experiment_name }}/docker_run.sh"
        mode: 0755
      vars:
        command: pytest -vv --durations=0 -m "not system and not integration"
      tags: testing

    - name: Run unit tests in a container
      community.docker.docker_container:
        name: simod_testing
        image: "{{ docker_image }}"
        command: /bin/bash -c "cd /usr/src/Simod/input && ./docker_run.sh"
        volumes:
          - "{{ base_dir }}/{{ experiment_name }}:/usr/src/Simod/input"
          - "{{ base_dir }}/{{ experiment_name }}/output:/usr/src/Simod/outputs"
        state: started
        recreate: yes
        restart_policy: no
        tty: yes
        detach: no
        cleanup: yes
      vars:
        docker_image: nokal/simod:latest
      register: docker_testing
      ignore_errors: yes
      tags: testing