@startuml Simod
skinparam componentStyle rectangle


component Discovery {
    component InterArrivalDistribution
    component TaskEvaluator
}

component ProcessModel {
    [BPMGraph]
    [BPMNReaderWriter]
}

component Simulation

component Optimizer {
    component Structure {
        component StructureSimulationParametersMiner {
            component ActivityResource1
            component Calendars1
            component Distributions1
            component GatewayProbabilities1
            component ResourceProfiles1
        }

        component StructureOptimizer
        component StructureMiner

        StructureOptimizer ..> StructureMiner
        StructureOptimizer ..> StructureSimulationParametersMiner
    }

    component Calendars {
        component CalendarSimulationParametersMiner {
            component ActivityResource2
            component Calendars2
            component Distributions2
            component GatewayProbabilities2
            component ResourceProfiles2
        }

        component CalendarOptimizer

        CalendarOptimizer ..> CalendarSimulationParametersMiner
    }
}

node Prosimos

StructureSimulationParametersMiner ..> Discovery
StructureSimulationParametersMiner .u.> ProcessModel
CalendarSimulationParametersMiner .u.> ProcessModel
StructureSimulationParametersMiner ..> Simulation
CalendarSimulationParametersMiner ..> Simulation
Simulation ..> Prosimos

@enduml