@startuml Simod2
skinparam componentStyle rectangle

node Prosimos

component Simulation {
    component SimulationParametersMiner {
        component ActivityResource
        component Calendars
        component Distributions
        component GatewayProbabilities
        component ResourceProfiles
        component InterArrivalDistribution
        component TaskEvaluator
    }
    component Simulator
}

component ProcessModel {
    [BPMGraph]
    [BPMNReaderWriter]
}

component Optimizer {
    component StructureOptimizer {
        component "HyperOptimizer" as HyperOptimizer2
    }
    component StructureMiner

    StructureOptimizer ..> StructureMiner


    component CalendarOptimizer {
        component HyperOptimizer
    }
}

Simulator ..> Prosimos

SimulationParametersMiner ..> BPMNReaderWriter

StructureOptimizer ..> Simulation
CalendarOptimizer ..> Simulation

@enduml