name: Build & Test

on:
  push:
    branches: [ new_replayer ]
  pull_request:
    branches: [ new_replayer ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: new_replayer
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -e .
    - name: Test with pytest
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          pytest -k test_optimize
