name: Build & Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nokal/simod-testing:v1.2.1
    env:
      BRANCH_NAME: master
    steps:
      - name: Test
        run: |
          cd /usr/src && bash test_simod.sh
      - name: Snyk Scan
        uses: snyk/actions@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
